### ISSUE TITLE
Adding the contributing.md file

### ISSUE THREAD

**Issue by ashishrana160796** [arana-initiatives/arana-initiatives.github.io#11]
Add the attached CONTRIBUTING.MD file for this github repository and your PR will be accepted. But, before making a commit do update the `.txt` extension to the `.md` extension type. 

Upload file: [CONTRIBUTING.txt](https://github.com/arana-initiatives/arana-initiatives.github.io/files/5469273/CONTRIBUTING.txt)

Thanks in advance, help plant more trees with Hacktoberfest !! Also, sorry for opening this issue at such a late stage was per-occupied with with personal work.

__Note:__ This is an issue for beginner github users only and will be assigned to that user only after review.

**Comment by claudemuller** [comment]
Hey @ashishrana160796. What definition does a "beginner" take? Someone who is new to Github or someone who is new to contributing to OSS?

**Comment by ashishrana160796** [comment]
Hi @claudemuller, a _'beginner'_ would be someone who is new to github. Like someone learning to make their first PR. As it's a very easy task to complete would be best suited for a newcomer to git.

Thanks for your comment and interest !!

**Comment by claudemuller** [comment]
Aha! Understood, thanks @ashishrana160796 - I guess I'm beyond that stage :)
